def getGitBranchName() {
    def branch = 'unknown'
    try {
        def stdout = new ByteArrayOutputStream()
        exec {
            commandLine 'git', 'rev-parse', '--abbrev-ref', 'HEAD'
            standardOutput = stdout
        }
        branch = stdout.toString().trim()
    } catch (Exception ignored) {}
    return branch
}

// Set version from branch name
version = getGitBranchName()

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            groupId = 'uz.narzullayev.javohir'
            artifactId = 'common'
            version = project.version
        }
    }

    repositories {
        maven {
            name = "nexus"
            def isSnapshot = version.endsWith("-SNAPSHOT")
            url = uri(isSnapshot
                    ? "http://localhost:8081/repository/maven-snapshots/"
                    : "http://localhost:8081/repository/maven-releases/")
            allowInsecureProtocol = true
            credentials {
                username = findProperty("nexusUsername") ?: "common"
                password = findProperty("nexusPassword") ?: "admin"
            }
        }
    }
}