plugins {
    id 'java'
    id 'maven-publish'
}

group = 'uz.narzullayev.javohir'

def artifactVersion = '1.1' // Default version

version = project.hasProperty('release') ? artifactVersion : "${artifactVersion}-SNAPSHOT"

repositories {
    mavenCentral()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            name = "nexus"
            def releasesRepoUrl = uri("http://localhost:8081/repository/maven-releases/")
            def snapshotsRepoUrl = uri("http://localhost:8081/repository/maven-snapshots/")
            url = version.endsWith("SNAPSHOT") ? snapshotsRepoUrl : releasesRepoUrl
            allowInsecureProtocol = true
            credentials {
                username = findProperty('nexusUser') ?: System.getenv('NEXUS_USER') ?: 'common'
                password = findProperty('nexusPassword') ?: System.getenv('NEXUS_PASSWORD') ?: 'admin'
            }
        }
    }
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}
