plugins {
    id 'java'
    id 'maven-publish'
}

group = 'uz.narzullayev.javohir'
version = '1.1'

repositories {
    mavenCentral()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            name = "nexus"
            url = uri("http://localhost:8081/repository/maven-releases/")
            allowInsecureProtocol = true
            credentials {
                username = 'common'
                password = 'admin'
            }
        }
    }
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}